# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: serdarkalayci/mongo-movies
    container_name: movie-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: movies

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081

  movie-app:
    image: serdarkalayci/movieapi
    container_name: movieapi
    ports: 
      - 5002:80
    environment:
        MongoDatabaseSettings_ConnectionString: mongodb://mongo:27017
        MongoDatabaseSettings_DatabaseName: movies
        MongoDatabaseSettings_MoviesCollectionName: movie